"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { calculateDiagnostic, DiagnosticResult, LeadInput, normalizeNumber, validateLead } from "../lib/diagnostic";

type FormState = { name: string; whatsapp: string; city: string; monthlyRevenue: string; monthlyOrders: string; averageTicket: string; consent: boolean; honeypot: string };
const initialForm: FormState = { name: "", whatsapp: "", city: "", monthlyRevenue: "", monthlyOrders: "", averageTicket: "", consent: false, honeypot: "" };
function readAttribution() { if (typeof window === "undefined") return {}; const params = new URLSearchParams(window.location.search); return Object.fromEntries(["utm_source", "utm_medium", "utm_campaign", "utm_content", "utm_term"].map((key) => [key, params.get(key) || "instagram"])); }

export default function Home() {
  const [form, setForm] = useState<FormState>(initialForm); const [errors, setErrors] = useState<Record<string, string>>({}); const [result, setResult] = useState<DiagnosticResult | null>(null); const [submitting, setSubmitting] = useState(false); const [saveStatus, setSaveStatus] = useState<"idle" | "saved" | "pending">("idle"); const attribution = useMemo(readAttribution, []);
  useEffect(() => { document.documentElement.style.scrollBehavior = "smooth"; return () => { document.documentElement.style.scrollBehavior = "auto"; }; }, []);
  function update(field: keyof FormState, value: string | boolean) { setForm((current) => ({ ...current, [field]: value })); if (errors[field]) setErrors((current) => ({ ...current, [field]: "" })); }
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const input: LeadInput = { name: form.name, whatsapp: form.whatsapp, city: form.city, monthlyRevenue: normalizeNumber(form.monthlyRevenue), monthlyOrders: normalizeNumber(form.monthlyOrders), averageTicket: normalizeNumber(form.averageTicket), consent: form.consent, honeypot: form.honeypot }; const validation = validateLead(input); setErrors(validation as Record<string, string>); if (Object.keys(validation).length > 0) return; const nextResult = calculateDiagnostic(input); setResult(nextResult); setSubmitting(true); setSaveStatus("pending"); try { const response = await fetch("/api/leads", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...input, ...attribution, diagnostic: nextResult }) }); const data = await response.json(); setSaveStatus(response.ok && data.configured === true ? "saved" : "idle"); } catch { setSaveStatus("idle"); } finally { setSubmitting(false); window.setTimeout(() => document.getElementById("diagnostico")?.scrollIntoView({ behavior: "smooth", block: "start" }), 50); } }
  const whatsappNumber = process.env.NEXT_PUBLIC_WHATSAPP_NUMBER?.replace(/\D/g, "") || ""; const whatsappMessage = encodeURIComponent("Olá, Vitor! Fiz o diagnóstico do meu delivery e quero agendar minha consultoria gratuita de 30 minutos.");
  return <main>
    <section className="hero shell"><div className="topbar"><span className="brand-mark">V</span><span>VITOR DO DELIVERY</span><span className="topbar-note">Diagnóstico rápido para quem vende no iFood</span></div><div className="hero-grid"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-dot" /> ANÁLISE GRATUITA EM 2 MINUTOS</p><h1>Descubra o que está travando o crescimento do seu delivery.</h1><p className="hero-text">Responda 6 perguntas sobre a sua operação e receba uma leitura prática dos gargalos que podem estar deixando dinheiro na mesa.</p><div className="proof-row"><div className="proof-icon">↗</div><div><strong>Mais clareza para decidir.</strong><span>Sem achismo. Com os números da sua operação.</span></div></div></div>
      <div className="form-card" id="formulario"><div className="card-heading"><span className="step-pill">01</span><div><p className="card-kicker">COMECE PELO SEU CENÁRIO</p><h2>Vamos encontrar sua oportunidade.</h2></div></div><form onSubmit={handleSubmit} noValidate><div className="form-grid two"><Field label="Seu nome" name="name" value={form.name} placeholder="Como posso te chamar?" error={errors.name} onChange={(v) => update("name", v)} /><Field label="WhatsApp" name="whatsapp" value={form.whatsapp} placeholder="(11) 99999-9999" error={errors.whatsapp} onChange={(v) => update("whatsapp", v)} /></div><Field label="Cidade / estado" name="city" value={form.city} placeholder="Ex.: Campinas - SP" error={errors.city} onChange={(v) => update("city", v)} /><div className="form-grid three"><Field label="Faturamento mensal" name="monthlyRevenue" value={form.monthlyRevenue} placeholder="R$ 25.000" inputMode="decimal" error={errors.monthlyRevenue} onChange={(v) => update("monthlyRevenue", v)} /><Field label="Pedidos / mês" name="monthlyOrders" value={form.monthlyOrders} placeholder="450" inputMode="numeric" error={errors.monthlyOrders} onChange={(v) => update("monthlyOrders", v)} /><Field label="Ticket médio" name="averageTicket" value={form.averageTicket} placeholder="R$ 55" inputMode="decimal" error={errors.averageTicket} onChange={(v) => update("averageTicket", v)} /></div><input className="honeypot" tabIndex={-1} autoComplete="off" aria-hidden="true" value={form.honeypot} onChange={(e) => update("honeypot", e.target.value)} /><label className={`consent ${errors.consent ? "has-error" : ""}`}><input type="checkbox" checked={form.consent} onChange={(e) => update("consent", e.target.checked)} /><span>Concordo em receber o diagnóstico e o contato sobre a consultoria gratuita.</span></label>{errors.consent && <p className="field-error consent-error">{errors.consent}</p>}<button className="primary-button" type="submit" disabled={submitting}>{submitting ? "Montando sua análise..." : "Gerar meu diagnóstico gratuito"}<span>↗</span></button><p className="privacy-note">Seus dados ficam protegidos e serão usados apenas para falar sobre o seu delivery.</p></form></div></div></section>
    {result && <section className="result-section shell" id="diagnostico"><div className="result-intro"><p className="eyebrow"><span className="eyebrow-dot" /> SEU DIAGNÓSTICO ESTÁ PRONTO</p><h2>{result.headline}</h2><p>{result.summary}</p><span className="result-badge">{result.scoreLabel}</span></div><div className="result-grid">{result.items.map((item) => <article className={`diagnostic-card ${item.tone}`} key={item.title}><span className="result-label">{item.label}</span><h3>{item.title}</h3><p>{item.detail}</p><div className="action-line"><span>→</span><strong>{item.action}</strong></div></article>)}</div><div className="consultation-card"><div><p className="card-kicker">SEU PRÓXIMO PASSO</p><h3>Você ganhou uma consultoria gratuita de 30 minutos.</h3><p>Eu vou olhar para os números do seu delivery e te mostrar onde existe mais potencial de crescimento.</p></div>{whatsappNumber ? <a className="whatsapp-button" href={`https://wa.me/${whatsappNumber}?text=${whatsappMessage}`} target="_blank" rel="noreferrer">Quero agendar minha consultoria <span>↗</span></a> : <span className="setup-note">WhatsApp será conectado em breve</span>}</div>{saveStatus === "saved" && <p className="save-message">✓ Seus dados foram enviados. Agora é só chamar no WhatsApp para reservar seu horário.</p>}{saveStatus === "idle" && <p className="save-message muted">Sua análise está pronta. O envio para acompanhamento será ativado assim que a planilha for conectada.</p>}</section>}
    <footer className="footer shell"><span>© {new Date().getFullYear()} Vitor do Delivery</span><span>Estratégia para operações que querem vender mais.</span></footer>
  </main>;
}
function Field({ label, name, value, placeholder, error, onChange, inputMode }: { label: string; name: string; value: string; placeholder: string; error?: string; onChange: (value: string) => void; inputMode?: "decimal" | "numeric" }) { return <label className="field"><span>{label}</span><input name={name} value={value} placeholder={placeholder} inputMode={inputMode} onChange={(e) => onChange(e.target.value)} aria-invalid={Boolean(error)} />{error && <small className="field-error">{error}</small>}</label>; }
